"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# *** Configuração padrão do Django ***

## SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-+3#%w-w277+qlbys5nl$86q#o#s%j$07#8cpn3(bh_mtbtm!mg'
#
## SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
#
#ALLOWED_HOSTS = []

# *** Configuração para o ambiente ***
import os
from dotenv import load_dotenv

load_dotenv()  # Carrega variáveis do .env

# Configurações críticas com fallback seguro
SECRET_KEY = os.getenv('SECRET_KEY', 'fallback-key-32-chars-dev-only')  # Adicione um fallback para desenvolvimento

# DEBUG com tratamento mais robusto
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'  # Converte para booleano corretamente

# ALLOWED_HOSTS com fallback e tratamento para string vazia
allowed_hosts = os.getenv('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = allowed_hosts.split(',') if allowed_hosts else []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',       # Para APIs
    'corsheaders',
    'sala_leitura',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Adicione no topo
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'sala_leitura.Usuario'

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Redirecionamentos Login e Logout
LOGIN_REDIRECT_URL = '/sala_leitura/home/'
LOGOUT_REDIRECT_URL = '/sala_leitura/'

# Modificações para uso do React:
# Permita requisições do React (em desenvolvimento)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000", # URL do seu frontend React
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ]
}